# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

name: $(version_major).$(version_minor).$(Rev:r)

trigger:
- master

variables:
  version_major: 0
  version_minor: 1

pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: |
        echo $(Build.BuildNumber)
        echo $(Build.SourcesDirectory)
        echo $(Build.BinariesDirectory)
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        make
        pwd
        ls
      displayName: 'make'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: 'primes_in_range'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
- stage: Deploy
  jobs:
  - deployment: DeployJob
    environment:
      name: Dev
      resourceName: DEV1
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo Hello world > C:\Temp\deploy.txt
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: C:\temp
