# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

name: $(version_major).$(version_minor).$(Rev:r)

trigger:
- master

variables:
  version_major: 0
  version_minor: 1

pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: |
        echo $(Build.BuildNumber)
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: make
      displayName: 'make'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**/$(BuildConfiguration)/**/primes_in_range'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
- stage: Release
  jobs:
  - job: ReleaseJob
    steps:
    - script: |
        echo $(release_name)

